create table COCKTAIL_SHOPPING_LIST (
    SHOPPING_LIST_ID UUID,
    COCKTAIL_ID UUID,
FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST (ID),
FOREIGN KEY (COCKTAIL_ID) REFERENCES COCKTAIL (ID)
);